// In-memory persistent fallback store when MongoDB service is not running locally
// Pre-populated with realistic agricultural marketplace records

export const fallbackStore = {
  users: [
    {
      id: 'usr-1',
      _id: 'usr-1',
      name: 'Priya Sharma',
      email: 'buyer@farmdirect.io',
      role: 'buyer',
      phone: '+91 98765 43210',
      address: 'Flat 402, Green Meadows Residency, Shivaji Nagar, Pune, Maharashtra 411005'
    },
    {
      id: 'usr-2',
      _id: 'usr-2',
      name: 'Rajesh Patel',
      email: 'farmer@farmdirect.io',
      role: 'farmer',
      phone: '+91 98260 12489',
      address: 'Village Berasia, Bhopal District, Madhya Pradesh'
    },
    {
      id: 'usr-3',
      _id: 'usr-3',
      name: 'Admin Operations',
      email: 'admin@farmdirect.io',
      role: 'admin',
      phone: '+91 99999 88888',
      address: 'FarmDirect HQ, Sector 5, Bhopal'
    }
  ],

  farmers: [
    {
      id: 'farmer-1',
      _id: 'farmer-1',
      name: 'Rajesh Patel',
      farmerName: 'Rajesh Patel',
      farmName: 'Rajesh Organic Farms',
      location: 'Bhopal, Madhya Pradesh',
      state: 'Madhya Pradesh',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
      profileImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
      coverImage: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1200&auto=format&fit=crop&q=80',
      experienceYears: 15,
      rating: 4.8,
      reviewsCount: 142,
      acres: 12,
      ordersCount: 128,
      distanceKm: 8.4,
      verified: true,
      certifications: ['India Organic (NPOP)', 'Jaivik Bharat', 'PGS-India Green'],
      specialtyCrops: ['Cherry Tomatoes', 'Red Onions', 'Sehore Sharbati Wheat', 'Papaya'],
      bio: 'Pioneering organic soil stewardship in the Bhopal countryside for over 15 years.',
      phone: '+91 98260 12489',
      establishedYear: 2009,
      bankSettlement: 'State Bank of India (Ending in 4092)'
    },
    {
      id: 'farmer-2',
      _id: 'farmer-2',
      name: 'Balwinder Singh',
      farmerName: 'Balwinder Singh',
      farmName: 'Singh Heritage Agri',
      location: 'Ludhiana, Punjab',
      state: 'Punjab',
      avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=300&auto=format&fit=crop&q=80',
      profileImage: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=300&auto=format&fit=crop&q=80',
      coverImage: 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=1200&auto=format&fit=crop&q=80',
      experienceYears: 22,
      rating: 4.9,
      reviewsCount: 218,
      acres: 35,
      ordersCount: 245,
      distanceKm: 18.2,
      verified: true,
      certifications: ['GlobalGAP Compliant', 'Punjab Agri Certified'],
      specialtyCrops: ['Shimla Royal Apples', 'Moong Dal', 'Basmati Rice'],
      bio: 'Fourth-generation farming family combining heritage agro-ecological wisdom with precision laser land leveling and drip systems.',
      phone: '+91 98140 55198',
      establishedYear: 2002,
      bankSettlement: 'Punjab National Bank (Ending in 7731)'
    },
    {
      id: 'farmer-3',
      _id: 'farmer-3',
      name: 'Ramesh Patil',
      farmerName: 'Ramesh Patil',
      farmName: 'Sahyadri Agro',
      location: 'Nashik, Maharashtra',
      state: 'Maharashtra',
      avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=300&auto=format&fit=crop&q=80',
      profileImage: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=300&auto=format&fit=crop&q=80',
      coverImage: 'https://images.unsplash.com/photo-1592417817098-8f3d6ef23153?w=1200&auto=format&fit=crop&q=80',
      experienceYears: 12,
      rating: 4.7,
      reviewsCount: 310,
      acres: 18,
      ordersCount: 340,
      distanceKm: 14.5,
      verified: true,
      certifications: ['Maharashtra Jaivik प्रमाणीकरण', 'Water Stewardship Certified'],
      specialtyCrops: ['Nashik Red Onion', 'Thompson Seedless Grapes', 'Pomegranate'],
      bio: 'Nestled in the lush valleys of Nashik, we utilize bio-fermented mulches and drip nutrition to raise premium onions.',
      phone: '+91 94222 38901',
      establishedYear: 2012,
      bankSettlement: 'Bank of Baroda (Ending in 1184)'
    }
  ],

  products: [
    {
      id: 'prod-1',
      _id: 'prod-1',
      name: 'Fresh Tomato',
      category: 'Vegetables',
      variety: 'Cherry & Hybrid Tomato',
      grade: 'Grade A',
      shelfLife: '6 - 8 Days',
      minOrderQty: '5 kg',
      availableQty: 1200,
      unit: 'kg',
      price: 38,
      marketPrice: 45,
      farmerPrice: 30,
      logisticsFee: 4,
      platformFee: 4,
      rating: 4.8,
      reviewsCount: 142,
      isOrganic: true,
      isPopular: true,
      isLocal: true,
      inStock: true,
      location: 'Bhopal, Madhya Pradesh',
      state: 'Madhya Pradesh',
      farmerId: 'farmer-1',
      farmerName: 'Rajesh Patel',
      farmName: 'Rajesh Organic Farms',
      farmerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      image: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=600&auto=format&fit=crop&q=80',
      description: 'Farm-fresh, naturally ripened vibrant red tomatoes harvested at peak sweetness. Zero chemical pesticide residue.',
      traditionalSupplyChain: [
        { role: 'Farmer', price: 18, label: 'Farmer baseline' },
        { role: 'Trader', price: 24, label: 'Mandi aggregator fee' },
        { role: 'Wholesaler', price: 30, label: 'Regional mandi markup' },
        { role: 'Retailer', price: 40, label: 'Local store markup' },
        { role: 'Consumer', price: 45, label: 'Final consumer shelf price' }
      ]
    },
    {
      id: 'prod-2',
      _id: 'prod-2',
      name: 'Potato (Jyoti)',
      category: 'Vegetables',
      variety: 'Kufri Jyoti',
      grade: 'Grade 1 (Medium - Large)',
      shelfLife: '3 - 4 Weeks',
      minOrderQty: '10 kg',
      availableQty: 4500,
      unit: 'kg',
      price: 26,
      marketPrice: 34,
      farmerPrice: 20,
      logisticsFee: 3,
      platformFee: 3,
      rating: 4.7,
      reviewsCount: 98,
      isOrganic: false,
      isPopular: true,
      isLocal: true,
      inStock: true,
      location: 'Indore, Madhya Pradesh',
      state: 'Madhya Pradesh',
      farmerId: 'farmer-6',
      farmerName: 'Vikramaditya Rathore',
      farmName: 'Malwa Crops',
      farmerAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
      image: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=600&auto=format&fit=crop&q=80',
      description: 'High dry-matter Jyoti potatoes directly from the rich Malwa soil. Firm texture, low sugar content.',
      traditionalSupplyChain: [
        { role: 'Farmer', price: 12, label: 'Farm gate' },
        { role: 'Trader', price: 17, label: 'Cold store intermediary' },
        { role: 'Wholesaler', price: 23, label: 'APMC Wholesaler' },
        { role: 'Retailer', price: 29, label: 'Retail distributor' },
        { role: 'Consumer', price: 34, label: 'Market price' }
      ]
    },
    {
      id: 'prod-4',
      _id: 'prod-4',
      name: 'Shimla Royal Apple',
      category: 'Fruits',
      variety: 'Royal Delicious Red',
      grade: 'A+ Extra Fancy',
      shelfLife: '3 - 4 Weeks',
      minOrderQty: '5 kg (Crate)',
      availableQty: 1800,
      unit: 'kg',
      price: 145,
      marketPrice: 195,
      farmerPrice: 120,
      logisticsFee: 15,
      platformFee: 10,
      rating: 4.9,
      reviewsCount: 218,
      isOrganic: true,
      isPopular: true,
      isLocal: false,
      inStock: true,
      location: 'Ludhiana, Punjab',
      state: 'Punjab',
      farmerId: 'farmer-2',
      farmerName: 'Balwinder Singh',
      farmName: 'Singh Heritage Agri',
      farmerAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
      image: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=600&auto=format&fit=crop&q=80',
      description: 'Crisp, aromatic high-altitude Royal Delicious apples with natural wax and intense mountain sweetness.',
      traditionalSupplyChain: [
        { role: 'Farmer', price: 65, label: 'Orchard rate' },
        { role: 'Trader', price: 95, label: 'CA cold store agent' },
        { role: 'Wholesaler', price: 130, label: 'Azadpur mandi wholesaler' },
        { role: 'Retailer', price: 170, label: 'Metro retailer' },
        { role: 'Consumer', price: 195, label: 'Retail price' }
      ]
    },
    {
      id: 'prod-5',
      _id: 'prod-5',
      name: 'Nashik Red Onion',
      category: 'Vegetables',
      variety: 'Garwa Dark Red',
      grade: 'Grade A (55mm+)',
      shelfLife: '6 - 8 Weeks',
      minOrderQty: '10 kg',
      availableQty: 6000,
      unit: 'kg',
      price: 28,
      marketPrice: 38,
      farmerPrice: 21,
      logisticsFee: 3.5,
      platformFee: 3.5,
      rating: 4.7,
      reviewsCount: 310,
      isOrganic: false,
      isPopular: true,
      isLocal: true,
      inStock: true,
      location: 'Nashik, Maharashtra',
      state: 'Maharashtra',
      farmerId: 'farmer-3',
      farmerName: 'Ramesh Patil',
      farmName: 'Sahyadri Agro',
      farmerAvatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
      image: 'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?w=600&auto=format&fit=crop&q=80',
      description: 'Renowned Nashik dark red onions known for pungency, thick protective skin, and long storability.',
      traditionalSupplyChain: [
        { role: 'Farmer', price: 12, label: 'Lasalgaon Mandi base' },
        { role: 'Trader', price: 18, label: 'Bidding middleman' },
        { role: 'Wholesaler', price: 26, label: 'Secondary mandi wholesaler' },
        { role: 'Retailer', price: 33, label: 'Kirana markup' },
        { role: 'Consumer', price: 38, label: 'Consumer purchase price' }
      ]
    }
  ],

  orders: [
    {
      id: 'FD-10294',
      _id: 'FD-10294',
      orderNumber: 'FD-10294',
      orderDate: '2025-05-12T10:30:00Z',
      status: 'Processing',
      buyerId: 'buyer-demo',
      buyerName: 'Rohan Deshmukh',
      deliveryAddress: 'Flat 402, Green Meadows Residency, Shivaji Nagar, Pune, Maharashtra 411005',
      paymentMethod: 'UPI (GPay)',
      paymentStatus: 'Escrow Held',
      items: [
        {
          productId: 'prod-1',
          name: 'Fresh Tomato',
          image: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=200&auto=format&fit=crop&q=80',
          farmerName: 'Rajesh Patel',
          quantity: 50,
          unit: 'kg',
          unitPrice: 38,
          total: 1900
        },
        {
          productId: 'prod-2',
          name: 'Potato (Jyoti)',
          image: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=200&auto=format&fit=crop&q=80',
          farmerName: 'Vikramaditya Rathore',
          quantity: 40,
          unit: 'kg',
          unitPrice: 26,
          total: 1040
        }
      ],
      subtotal: 2940,
      deliveryFee: 180,
      platformFee: 60,
      totalAmount: 3060,
      total: 3060,
      farmerEarnings: 2540,
      timeline: [
        { step: 'Order Confirmed', time: '12 May 2025, 10:30 AM', completed: true, current: false, description: 'Order verified & payment confirmed via UPI' },
        { step: 'Farmer Preparing', time: '12 May 2025, 01:15 PM', completed: true, current: true, description: 'Grading and crating fresh produce' },
        { step: 'Picked Up', time: 'Est. 13 May, 07:00 AM', completed: false, current: false, description: 'Refrigerated logistics van will collect crates' },
        { step: 'Out for Delivery', time: 'Est. 13 May, 02:00 PM', completed: false, current: false, description: 'Last-mile dispatch to your address' },
        { step: 'Delivered', time: 'Est. 13 May, 05:30 PM', completed: false, current: false, description: 'Handover complete' }
      ]
    }
  ],

  marketPrices: [
    {
      id: 'mp-1',
      _id: 'mp-1',
      commodity: 'Tomato (Hybrid)',
      location: 'Bhopal Mandi (Karond)',
      mandiLocation: 'Karond APMC, MP',
      marketAverage: 45,
      farmDirectPrice: 38,
      differencePercent: 18.4,
      unit: 'kg',
      trend: 'down',
      recommendedRange: '₹36 - ₹40 / kg',
      aiAdvisory: 'Mandi arrivals increased by 14% this morning. Direct farm-gate orders protect ₹8/kg surplus.',
      history: [
        { day: 'Mon', farmDirect: 39, mandi: 48 },
        { day: 'Tue', farmDirect: 38, mandi: 47 },
        { day: 'Wed', farmDirect: 38, mandi: 46 },
        { day: 'Thu', farmDirect: 37, mandi: 45 },
        { day: 'Fri', farmDirect: 38, mandi: 45 }
      ]
    },
    {
      id: 'mp-2',
      _id: 'mp-2',
      commodity: 'Potato (Jyoti)',
      location: 'Indore Mandi (Choithram)',
      mandiLocation: 'Choithram APMC, Indore',
      marketAverage: 34,
      farmDirectPrice: 26,
      differencePercent: 23.5,
      unit: 'kg',
      trend: 'stable',
      recommendedRange: '₹24 - ₹28 / kg',
      aiAdvisory: 'Cold storage release steady. FarmDirect bulk crates save ₹8 per kg vs city supermarkets.',
      history: [
        { day: 'Mon', farmDirect: 26, mandi: 34 },
        { day: 'Tue', farmDirect: 26, mandi: 35 },
        { day: 'Wed', farmDirect: 26, mandi: 34 },
        { day: 'Thu', farmDirect: 25, mandi: 33 },
        { day: 'Fri', farmDirect: 26, mandi: 34 }
      ]
    }
  ],

  communityPools: [
    {
      id: 'pool-1',
      _id: 'pool-1',
      productId: 'prod-1',
      productName: 'Fresh Tomato',
      variety: 'Hybrid Salad Tomato',
      image: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=500&auto=format&fit=crop&q=80',
      farmerName: 'Rajesh Patel',
      farmLocation: 'Bhopal, MP',
      currentDemandKg: 87,
      targetKg: 100,
      unit: 'kg',
      currentPrice: 38,
      unlockedPrice: 34,
      superPrice: 31,
      superTargetKg: 250,
      participantsCount: 14,
      endsInHours: 8,
      deliveryDate: 'Tomorrow, 5:00 PM',
      hubLocation: 'Shivaji Nagar Community Hub, Pune',
      status: 'Active'
    }
  ]
};
